name: learn-github-actions
run-name: ${{ github.actor }} unit tests
on:
  pull_request:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
